version: '3.1'

services:

  mysql-aster:
    build: $PWD/mysql
    container_name: "mysql-master"
    expose:
    - "3306"
    networks:
    - "my-net"
    volumes:
    - $PWD/mysql/master/data:/var/lib/mysql
    - $PWD/mysql/master/conf:/etc/mysql/mysql.conf.d
    - $PWD/mysql/master/log:/var/log/mysqld.log
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
networks:
  my-net:
    driver: bridge