version: '3.1'

services:

  my-nginx:
    build: $PWD/nginx
    container_name: "my-nginx"
    expose:
      - "80"
      - "443"
    networks:
      - "my-net"
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/conf.d:/etc/nginx/conf.d
      - $PWD/nginx/log:/wwwlogs
      - /www/wwwroot:/www
    ports:
      - "80:80"
      - "443:443"
networks:
  my-net:
    driver: bridge
